version: "3"
services:
  frontend:
    image: node:14
    user: 'node'
    restart: 'unless-stopped'
    stdin_open: true
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    command: 'bash -c "yarn && yarn start"'
    ports:
      - 3000:3000

  server:
    image: node:14
    user: 'node'
    restart: 'unless-stopped'
    working_dir: /home/node/app
    volumes:
      - ./server:/home/node/app
    command: 'bash -c "yarn && yarn start"'
    environment:
      PORT: 5000
    links:
      - 'mongo'
    ports: 
      - 5000:5000

  mongo:
    image: mongo:latest
    container_name: dbkiwi
    ports:
      - 27017:27017


